version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
  - package-ecosystem: "pip"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
